<script lang='ts'>
  import { onMount } from 'svelte';
  import Cookies from 'js-cookie';
  import headers from '$lib/requests/headers';
  import { goto } from '$app/navigation';
  import Loading from '../../lib/Loading.svelte';
  import ListCategories from '$lib/stock/ListCategories.svelte';

  let stocks:any[] = [];
  let stockchosen:any;
  let loading = true;
  let loadingCategories = true;
  let selectedStock = null;

  const id = Cookies.get('id');

  onMount(async () => {
    try {
      const response = await fetch(`http://localhost:8000/stocks/user/${id}/`, {
        headers: headers
      });
      const data = await response.json();
      stocks = data.stocks;
      stockchosen = stocks[0].id;
      loading = false;
    } catch (error) {
      console.error('Error fetching stock:', error);
    }
  });
</script>


  {#if loading}
  <Loading></Loading>
  {:else}
  <div id="list-stock">
    <div class="stock-container">
      {#each stocks as stock}
        <!-- svelte-ignore a11y-click-events-have-key-events -->
        <!-- svelte-ignore a11y-no-static-element-interactions -->
        <section class="stock-item {stockchosen === stock.id ? 'selected rotate-hor-center' : ''}" on:click={()=>stockchosen=stock.id}>
          <!-- svelte-ignore a11y-click-events-have-key-events -->
          <!-- svelte-ignore a11y-no-static-element-interactions -->
          <a id="cat-link" on:click={()=>stockchosen=stock.id}>{stock.name}</a>
        </section>
      {/each}
    </div>
  </div>
  <!--{#if loadingCategories}
  <Loading/>
  {:else}-->
<ListCategories {stockchosen} />
  <!--{/if}-->
  {/if}


<style>
  .stock-container {
    display: flex;
    overflow-x: auto;
    white-space: nowrap;
    -webkit-overflow-scrolling: touch;
  }

  /* Hide the scroll bar for webkit browsers (Chrome, Safari, etc.) */
  .stock-container::-webkit-scrollbar {
    display: none;
  }

  /* Add styles for the "selected" class */
  .selected {
    box-shadow: 0px 16px 48px 0px rgba(0, 0, 0, 0.176);
  }

  #cat-link {
    color: black;
    text-decoration: none;
  }

  #list-stock {
    font-size: 26px;
    padding: 10px;
    display: flex; /* Change to flex to ensure items are in a row */
    overflow-x: auto; /* Enable horizontal scrolling */
    white-space: nowrap; /* Prevent items from wrapping to the next line */
  }

  .stock-item {
    background-color: var(--blue-color);
    width: 30vw;
    height: 10vw;
    margin: 10px;
    padding: 10px;
    border-radius: 20px;
    cursor: pointer;
    text-align: center;
    word-wrap: break-word;
  }

  .rotate-hor-center {
	-webkit-animation: rotate-hor-center 0.5s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
	        animation: rotate-hor-center 0.5s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-8-5 15:50:42
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation rotate-hor-center
 * ----------------------------------------
 */
 @-webkit-keyframes rotate-hor-center {
  0% {
    -webkit-transform: rotateX(0);
            transform: rotateX(0);
  }
  100% {
    -webkit-transform: rotateX(-360deg);
            transform: rotateX(-360deg);
  }
}
@keyframes rotate-hor-center {
  0% {
    -webkit-transform: rotateX(0);
            transform: rotateX(0);
  }
  100% {
    -webkit-transform: rotateX(-360deg);
            transform: rotateX(-360deg);
  }
}
</style>